# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: supertrade/v1/trade.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "supertrade/v1/trade.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19supertrade/v1/trade.proto\x12\rsupertrade.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\x80\x01\n\x06\x45quity\x12.\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x04time\x12\x16\n\x06\x65quity\x18\x02 \x01(\x01R\x06\x65quity\x12\x12\n\x04\x63\x61sh\x18\x03 \x01(\x01R\x04\x63\x61sh\x12\x1a\n\x08\x64rawdown\x18\x04 \x01(\x01R\x08\x64rawdown"\xcf\x01\n\x08Position\x12\x16\n\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x16\n\x06shares\x18\x02 \x01(\x03R\x06shares\x12\x1b\n\tavg_price\x18\x03 \x01(\x01R\x08\x61vgPrice\x12\x14\n\x05price\x18\x04 \x01(\x01R\x05price\x12!\n\x0cmarket_value\x18\x05 \x01(\x01R\x0bmarketValue\x12%\n\x0eunrealized_pnl\x18\x06 \x01(\x01R\runrealizedPnl\x12\x16\n\x06weight\x18\x07 \x01(\x01R\x06weight"\xc3\x01\n\tPortfolio\x12.\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x04time\x12\x16\n\x06\x65quity\x18\x02 \x01(\x01R\x06\x65quity\x12\x12\n\x04\x63\x61sh\x18\x03 \x01(\x01R\x04\x63\x61sh\x12\x35\n\tpositions\x18\x04 \x03(\x0b\x32\x17.supertrade.v1.PositionR\tpositions\x12#\n\rnum_positions\x18\x05 \x01(\x05R\x0cnumPositions"\xd8\x01\n\x04\x46ill\x12.\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x04time\x12\x16\n\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n\x04side\x18\x03 \x01(\tR\x04side\x12\x16\n\x06shares\x18\x04 \x01(\x03R\x06shares\x12\x14\n\x05price\x18\x05 \x01(\x01R\x05price\x12\x12\n\x04\x63ost\x18\x06 \x01(\x01R\x04\x63ost\x12\x1a\n\x08notional\x18\x07 \x01(\x01R\x08notional\x12\x16\n\x06reason\x18\x08 \x01(\tR\x06reason"\xb5\x01\n\x03\x42\x61r\x12.\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x04time\x12\x16\n\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n\x04open\x18\x03 \x01(\x01R\x04open\x12\x12\n\x04high\x18\x04 \x01(\x01R\x04high\x12\x10\n\x03low\x18\x05 \x01(\x01R\x03low\x12\x14\n\x05\x63lose\x18\x06 \x01(\x01R\x05\x63lose\x12\x16\n\x06volume\x18\x07 \x01(\x01R\x06volumeb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "supertrade.v1.trade_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EQUITY"]._serialized_start = 78
    _globals["_EQUITY"]._serialized_end = 206
    _globals["_POSITION"]._serialized_start = 209
    _globals["_POSITION"]._serialized_end = 416
    _globals["_PORTFOLIO"]._serialized_start = 419
    _globals["_PORTFOLIO"]._serialized_end = 614
    _globals["_FILL"]._serialized_start = 617
    _globals["_FILL"]._serialized_end = 833
    _globals["_BAR"]._serialized_start = 836
    _globals["_BAR"]._serialized_end = 1017
# @@protoc_insertion_point(module_scope)
